del
jaykchen/demo_name_changed pull request #5
Opened 2022-09-01 17:57 UTC by amiiiiii830

delelte

2022-09-01 17:59 UTC, jaykchen reviewed
comment on pr from Amy

2022-09-01 18:01 UTC, jaykchen requested changes
can I reject it?

2022-09-01 18:02 UTC, jaykchen approved these changes

2022-09-01 20:16 UTC, amiiiiii830 commented
this is answer to the old thread

2022-09-02 15:37 UTC, jaykchen commented
testing new labels

2022-09-02 23:23 UTC, jaykchen reviewed
this is a comment to pr review

2022-09-02 23:40 UTC, jaykchen reviewed
the latedsct review comment

2022-09-02 23:48 UTC, jaykchen commented
> delelte

my comment added

2022-09-02 23:49 UTC, jaykchen requested changes
pls delete unwanted file

2022-09-02 23:52 UTC, jaykchen reviewed
atomic comment

2022-09-03 00:09 UTC, jaykchen commented on README.md
> -
PR review comment

2022-09-03 00:11 UTC, jaykchen commented on README.md
> -
this is a reply to the comment

2022-09-05 00:28 UTC, jaykchen commented on pages/index.vue
>    </div>
I have some comments

2022-09-05 00:30 UTC, jaykchen requested changes
this is new comment

2022-09-05 00:32 UTC, jaykchen commented on pages/index.vue
> +  <span> some random changes</span>
I don't like this addtion

2022-09-05 00:32 UTC, jaykchen commented on pages/index.vue
> +  <span> some random changes</span>
some reply to comment

2022-09-05 00:33 UTC, jaykchen approved these changes

2022-09-08 14:06 UTC, closed without merging

2022-09-08 14:06 UTC, jaykchen commented
rejected